# Kargo Warehouse - Simplified for v1.6.0 compatibility
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: flask-app
  namespace: flask-app-ns
  labels:
    app.kubernetes.io/name: flask-app
    kargo.akuity.io/project: flask-app-ns
spec:
  subscriptions:
    # Container image subscription - watches GHCR for new flask-app images
    - image:
        repoURL: ghcr.io/alkon/flask-app
        semverConstraint: ">=1.8.0"
        discoveryLimit: 10  # Limit to last 10 versions for performance