# Staging Environment Values - Managed by Kargo
# This file is automatically updated by Kargo when promoting from dev

# Image configuration
image:
  # Tag is automatically updated by Kargo from dev stage
  tag: "1.8.3"

# Staging-specific configurations
replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Staging uses LoadBalancer for external testing
service:
  type: LoadBalancer
  port: 5000

# Staging environment variables
env:
  - name: FLASK_ENV
    value: "staging"
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENABLE_METRICS
    value: "true"

# Enable autoscaling in staging
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

# Staging-specific annotations
podAnnotations:
  environment: "staging"
  managed-by: "kargo"
  monitoring: "enabled"