# Minimal Kargo Stage for API testing
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: flask-app-ns
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: flask-app
  promotionTemplate:
    spec:
      steps:
        - uses: git-commit
          config:
            path: kargo/argocd-apps/flask-app-dev.yaml
            messageFromSteps:
              to: commit-message