# Kargo Stage - Production Environment (simplified for v1.6.0 compatibility)
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: flask-app
  labels:
    environment: production
    kargo.akuity.io/project: flask-app
spec:
  # Subscribe from staging stage only
  subscriptions:
    upstreamStages:
      - name: staging
  
  # Manual promotion only for production
  promotionPolicy:
    autoPromotionEnabled: false
  
  # Update git repo with new versions
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/alkon/final-project-devops-repo.git
        writeBranch: features/k8s
        kustomize:
          images:
            - image: ghcr.io/alkon/flask-app
              path: kargo/argocd-apps/flask-app-prod.yaml