# Kargo Stage - Staging Environment (simplified for v1.6.0 compatibility)
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: flask-app
  labels:
    environment: staging
    kargo.akuity.io/project: flask-app
spec:
  # Subscribe from dev stage
  subscriptions:
    upstreamStages:
      - name: dev
  
  # Auto-promote after successful verification
  promotionPolicy:
    autoPromotionEnabled: true
  
  # Update git repo with new versions
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/alkon/final-project-devops-repo.git
        writeBranch: features/k8s
        kustomize:
          images:
            - image: ghcr.io/alkon/flask-app
              path: kargo/argocd-apps/flask-app-staging.yaml