# Kargo Stage - Staging Environment
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-ns
spec:
  # Promote from dev stage (not directly from warehouse)
  subscriptions:
    upstreamStages:
      - name: dev
  
  # Promotion mechanisms
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/alkon/final-gitops-proj.git
        writeBranch: main
        helm:
          images:
            - image: ghcr.io/alkon/flask-app
              key: image.tag
              value: IMAGE_TAG
              valuesFilePath: kargo/values/staging-values.yaml
  
  # Staging requires more thorough verification
  verification:
    analysisTemplates:
      - name: integration-tests
      - name: performance-tests
    args:
      - name: environment
        value: staging
      - name: test-duration
        value: "5m"
  
  # Optional: Auto-promotion from dev after 30 minutes of stability
  promotionPolicy:
    autoPromotionEnabled: true
    autoPromotionDelay: 30m